# Homebrew cask for authkit (authkit.app), the shared Secure-Enclave consent helper.
#
# The .app is Developer ID signed, notarized, and stapled, so a normal quarantined
# install clears Gatekeeper with no xattr/--no-quarantine hook. Install:
#
#   brew install yasyf/tap/authkit
#
# The whole .app must stay intact — the embedded provisioning profile that
# authorizes the Secure Enclave keychain-access-group is bundle-relative, and
# consumers resolve the binary straight from the Caskroom — so this is a
# 'stage_only' cask, never an 'app' move into /Applications nor a bare 'binary'
# symlink.
#
# This file is GENERATED by authkit's release.yml and pushed to the tap on every
# tagged release — do not hand-edit; change the template at
# authkit's .github/cask/authkit.rb.tmpl instead.
cask "authkit" do
  version "0.2.0"
  sha256 "1dcab22e92addd15cdce724206dcfb541d3fb44737b923a0f216a434dd96fcfb" # app

  url "https://github.com/yasyf/authkit/releases/download/v#{version}/authkit-v#{version}-darwin.zip"
  name "authkit"
  desc "Signed Secure-Enclave consent helper (Touch ID consent, attestation, key vault)"
  homepage "https://github.com/yasyf/authkit"

  depends_on macos: :ventura # parsed with a ">=" comparator: ventura or newer

  stage_only true
end
