# This file was generated by GoReleaser. DO NOT EDIT.
cask "binrun" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2980ee7d04b7b793d2bd5232f01d8421f3a9627a5829fd6d49f6c99da56719b4"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "373c7861d8fa9b4b1f46ee935bbca7a36e76704f86c2634d051be25f42b3a309"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "590518282cb501037dcdccf9559753ebdf349e9f972a6028045693690e18e808"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "60760cbfecbab3ec392bf7f6f898f83b627bd68476bd6620f45027dd8eccbf78"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "binrun"
  desc "Fetch, verify, and exec the exact artifact a descriptor pins — release binaries, Python tools, signed apps."
  homepage "https://github.com/yasyf/binrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "binrun"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/binrun"]
    end
  end

  # No zap stanza required

end
