# This file was generated by GoReleaser. DO NOT EDIT.
cask "binrun" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "f32f791631f96dbdd720084ae5bebd12133b1b863582351bb1418004c4360d71"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2d82cbbf98e3713c9f726a153fe647d7e5f62e607a701d3aaf09e62ceb11910"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d78a63d77e02d60eb9841cf04823cecfb8727d3e3e6f3ef71e1448e83b503ff4"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d50657612288fe6b22292249ab7e78ff868f600329048d1728f826bf6b60283"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "binrun"
  desc "Fetch, verify, and exec the exact artifact a descriptor pins — release binaries, Python tools, signed apps."
  homepage "https://github.com/yasyf/binrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "binrun"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/binrun"]
    end
  end

  # No zap stanza required
end
