# This file was generated by GoReleaser. DO NOT EDIT.
cask "binrun" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "fdd1bfc1d63f826d063c1b20a71869de7665a9e5527514f0d2cac4ec3315b7d2"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c9df1321cf5e63c56130494c1bc46978e0661c6564cb38a85e58d149fb53ca2"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c7ab174b6c0198e2679a7da89d8e24fb659e3b65ca71bf3bb3eb93008e1963e3"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "38bffa06c626486f6828d7adfc98cf57876e28ad817a0a262de4ef372b01bf46"
      url "https://github.com/yasyf/binrun/releases/download/v#{version}/binrun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "binrun"
  desc "Fetch, verify, and exec the exact artifact a descriptor pins — release binaries, Python tools, signed apps."
  homepage "https://github.com/yasyf/binrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "binrun"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/binrun"]
    end
  end

  # No zap stanza required
end
