# Homebrew cask for the Captain Hook helper app (Captain Hook.app).
#
# Developer ID signed, notarized, and stapled, so Gatekeeper validates the app
# offline; the postflight strips Homebrew's download quarantine so the first
# launch is silent. Modeled on daemonkit/templates/cask.rb.tmpl.
#
#   brew install --cask yasyf/tap/captain-hook
#
# GENERATED by the release workflow (render-formula) — do not hand-edit; change
# .github/cask/captain-hook.rb.tmpl instead. 12.18.1, 99783394d1c4a01cb47315b72165ca89592af3b0a25c04930012fccb1e5b424a, and
# https://github.com/yasyf/captain-hook/releases/download/v12.18.1/captain-hook-v12.18.1-darwin.zip are filled per release; every other value is literal.
cask "captain-hook" do
  version "12.18.1"
  sha256 "99783394d1c4a01cb47315b72165ca89592af3b0a25c04930012fccb1e5b424a" # app

  url "https://github.com/yasyf/captain-hook/releases/download/v12.18.1/captain-hook-v12.18.1-darwin.zip"
  name "Captain Hook"
  desc "Desktop notifications and PR-review widget for capt-hook"
  homepage "https://github.com/yasyf/captain-hook"

  depends_on macos: :sequoia # >= macOS 15, the DaemonKit deployment floor

  # A full .app bundle, never a bare `binary`: only a bundle staples its
  # notarization ticket and keeps a stable, bundle-keyed TCC/notification
  # identity across upgrades. The app is LSUIElement (no Dock icon) and
  # (re)registers its login-item agent via LoginItem.reconcile() on launch.
  app "Captain Hook.app"

  preflight do
    installed_app = "#{appdir}/Captain Hook.app"
    installed_binary = "#{installed_app}/Contents/MacOS/Captain Hook"
    if File.executable?(installed_binary)
      # Stop only the exact installed service before replacing the app.
      system_command installed_binary,
                     args: ["--stop-and-uninstall-service"],
                     must_succeed: true
    elsif Dir.exist?(installed_app)
      # Remove an incomplete bundle so Homebrew can install the replacement.
      FileUtils.rm_rf(installed_app)
    end
  end

  postflight do
    # Strip Homebrew's download quarantine so first launch is silent
    # (notarized + stapled).
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Captain Hook.app"],
                   must_succeed: false
    # Relaunch in the background (-g: no focus steal). Launching runs the app's
    # LoginItem.reconcile(), which re-registers the login-item agent.
    system_command "/usr/bin/open", args: ["-g", "#{appdir}/Captain Hook.app"], must_succeed: false
  end

  uninstall_preflight do
    installed_binary = "#{appdir}/Captain Hook.app/Contents/MacOS/Captain Hook"
    if File.executable?(installed_binary)
      # Stop only the exact installed service before Homebrew removes the app.
      system_command installed_binary,
                     args: ["--stop-and-uninstall-service"],
                     must_succeed: true
    end
  end

  zap trash: [
    "~/Library/LaunchAgents/com.yasyf.capt-hook.helper.plist",
    "~/Library/Containers/com.yasyf.capt-hook.helper.widget",
    "~/Library/Preferences/com.yasyf.capt-hook.helper.plist",
    "~/.capt-hook",
  ]
end
