# Homebrew cask for the Captain Hook helper app (Captain Hook.app).
#
# Developer ID signed, notarized, and stapled, so Gatekeeper validates the app
# offline; the postflight strips Homebrew's download quarantine so the first
# launch is silent. Modeled on daemonkit/templates/cask.rb.tmpl.
#
#   brew install --cask yasyf/tap/captain-hook
#
# GENERATED by the release workflow (render-formula) — do not hand-edit; change
# .github/cask/captain-hook.rb.tmpl instead. 12.2.0 and 9a672401c2645c64f420dc424335a43dc199003e8da5d244f9c5ed030e5b034f are
# filled per release; every other value is captain-hook-specific and literal.
cask "captain-hook" do
  version "12.2.0"
  sha256 "9a672401c2645c64f420dc424335a43dc199003e8da5d244f9c5ed030e5b034f" # app

  url "https://github.com/yasyf/captain-hook/releases/download/v#{version}/captain-hook-v#{version}-darwin.zip"
  name "Captain Hook"
  desc "Desktop notifications and PR-review widget for capt-hook"
  homepage "https://github.com/yasyf/captain-hook"

  depends_on macos: :sequoia # >= macOS 15, the DaemonKit deployment floor

  # A full .app bundle, never a bare `binary`: only a bundle staples its
  # notarization ticket and keeps a stable, bundle-keyed TCC/notification
  # identity across upgrades. The app is LSUIElement (no Dock icon) and
  # (re)registers its login-item agent via LoginItem.reconcile() on launch.
  app "Captain Hook.app"

  postflight do
    # Strip Homebrew's download quarantine so first launch is silent
    # (notarized + stapled).
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Captain Hook.app"],
                   must_succeed: false
    # Restart-on-upgrade: replace the resident process so it runs from the
    # freshly installed bundle. TERM for a clean exit, then KILL any straggler.
    system_command "/usr/bin/pkill", args: ["-TERM", "-x", "Captain Hook"], must_succeed: false
    sleep 1
    system_command "/usr/bin/pkill", args: ["-KILL", "-x", "Captain Hook"], must_succeed: false
    # Relaunch in the background (-g: no focus steal). Launching runs the app's
    # LoginItem.reconcile(), which re-registers the login-item agent.
    system_command "/usr/bin/open", args: ["-g", "#{appdir}/Captain Hook.app"], must_succeed: false
  end

  uninstall_preflight do
    # Boot the login-item agent OUT before the app is quit/removed — quitting
    # under a live SMAppService registration just triggers an instant relaunch.
    # `--unregister` calls SMAppService.agent(plistName:).unregister() and exits.
    system_command "#{appdir}/Captain Hook.app/Contents/MacOS/Captain Hook",
                   args: ["--unregister"],
                   must_succeed: false
  end

  # Runs AFTER uninstall_preflight: the agent is already booted out, so the quit
  # cannot race a relaunch.
  uninstall quit: "com.yasyf.capt-hook.helper"

  zap trash: [
    "~/Library/LaunchAgents/com.yasyf.capt-hook.helper.plist",
    "~/Library/Containers/com.yasyf.capt-hook.helper.widget",
    "~/Library/Preferences/com.yasyf.capt-hook.helper.plist",
    "~/.capt-hook",
  ]
end
