# Homebrew cask for the Captain Hook helper app (Captain Hook.app).
#
# Developer ID signed, notarized, and stapled, so Gatekeeper validates the app
# offline; the postflight strips Homebrew's download quarantine so the first
# launch is silent. Modeled on daemonkit/templates/cask.rb.tmpl.
#
#   brew install --cask yasyf/tap/captain-hook
#
# GENERATED by the release workflow (render-formula) — do not hand-edit; change
# .github/cask/captain-hook.rb.tmpl instead. 12.13.0, 0743f7086343b156a5faa221ba72e4d69cb8dd0342fd866acaedb70573f8ece8, and
# https://github.com/yasyf/captain-hook/releases/download/v12.13.0/captain-hook-v12.13.0-darwin.zip are filled per release; every other value is literal.
cask "captain-hook" do
  version "12.13.0"
  sha256 "0743f7086343b156a5faa221ba72e4d69cb8dd0342fd866acaedb70573f8ece8" # app

  url "https://github.com/yasyf/captain-hook/releases/download/v12.13.0/captain-hook-v12.13.0-darwin.zip"
  name "Captain Hook"
  desc "Desktop notifications and PR-review widget for capt-hook"
  homepage "https://github.com/yasyf/captain-hook"

  depends_on macos: :sequoia # >= macOS 15, the DaemonKit deployment floor

  # A full .app bundle, never a bare `binary`: only a bundle staples its
  # notarization ticket and keeps a stable, bundle-keyed TCC/notification
  # identity across upgrades. The app is LSUIElement (no Dock icon) and
  # (re)registers its login-item agent via LoginItem.reconcile() on launch.
  app "Captain Hook.app"

  preflight do
    installed_app = "#{appdir}/Captain Hook.app"
    if Dir.exist?(installed_app)
      system_command "#{installed_app}/Contents/MacOS/Captain Hook",
                     args: ["--stop-and-uninstall-service"],
                     must_succeed: true
    end
  end

  postflight do
    # Strip Homebrew's download quarantine so first launch is silent
    # (notarized + stapled).
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Captain Hook.app"],
                   must_succeed: false
    # Relaunch in the background (-g: no focus steal). Launching runs the app's
    # LoginItem.reconcile(), which re-registers the login-item agent.
    system_command "/usr/bin/open", args: ["-g", "#{appdir}/Captain Hook.app"], must_succeed: false
  end

  uninstall_preflight do
    # Remove the exact SMAppService registration, stop only processes belonging
    # to this stable bundle, and prove absence before Homebrew removes it.
    system_command "#{appdir}/Captain Hook.app/Contents/MacOS/Captain Hook",
                   args: ["--stop-and-uninstall-service"],
                   must_succeed: true
  end

  zap trash: [
    "~/Library/LaunchAgents/com.yasyf.capt-hook.helper.plist",
    "~/Library/Containers/com.yasyf.capt-hook.helper.widget",
    "~/Library/Preferences/com.yasyf.capt-hook.helper.plist",
    "~/.capt-hook",
  ]
end
