# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-guides" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "b85a05ee257ade804d1c03fc3b9dfd60907d6eefa52035b90ca336c90ce392df"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0833d234de2c045f07dddfcdfd714b4c75584c5f006304d033465eb4d2d28e20"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "45c3fbd5e56a2bce7da7c5a039fdea963394c7f99d3abc80a1cac12b57292cfb"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9bed65b8e715ac5a491881f1de94135c88d73529550d6f31db7601f2ffc1496c"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-guides"
  desc "Canonical agent guides as a shipped Go binary — render AGENTS.md, CLAUDE.md, and shell artifacts from embedded, versioned fragments"
  homepage "https://github.com/yasyf/cc-guides"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-guides"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-guides"]
    end
  end

  # No zap stanza required

end
