# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-guides" do
  version "0.1.39"

  on_macos do
    on_intel do
      sha256 "f13c6b45cfd47f33bea1a383a371c0ea80f36cf8a2d13ac31a10f7390547c08a"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f561b825d77254e33794b87e34244a69fb37538d0e028189a047b418d2d4c0cc"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b44793d394ba716d90f37c5c1c2e218bf11bf320a15010ea7712b7474b42f35a"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dab2ea8db301000f151177613a15ae6388dc0d31613d43cc632c2211a6a3bf4f"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-guides"
  desc "Canonical agent guides as a shipped Go binary — render AGENTS.md, CLAUDE.md, and shell artifacts from embedded, versioned fragments"
  homepage "https://github.com/yasyf/cc-guides"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-guides"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-guides"]
    end
  end

  # No zap stanza required

end
