# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-guides" do
  version "0.1.15"

  on_macos do
    on_intel do
      sha256 "1949101db9a922f998372b4a534b462f5d313ab773534067240d8912e878ac36"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e457f18f183beb0d16794ec69984acc194553eff408ea64af23343eaa0b413d"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f5758a0cd58a3d050360d56883d44ccab4c7a0b54b19a4c8313edc85554b97b3"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c026b8d42653d36718e6aa9479cb9c18dcb8aa64fd582f721512bbceb8b05870"
      url "https://github.com/yasyf/cc-guides/releases/download/v#{version}/cc-guides_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-guides"
  desc "Canonical agent guides as a shipped Go binary — render AGENTS.md, CLAUDE.md, and shell artifacts from embedded, versioned fragments"
  homepage "https://github.com/yasyf/cc-guides"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-guides"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-guides"]
    end
  end

  # No zap stanza required

end
