# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-orchestrate" do
  binary "cc-orchestrate", target: "cco"

  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f021ff60980d2a070b05c4a25453103264c59ebcac516515af681b4094cccdc6"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3940702691d8e6be0b6be3ca84ad05be0750f9f8ebf099d8709517b3a0c3dad2"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0c5bd6d115f0edd139fc5ad4282dedfea7c8769fe3136fe7ecc1e19045a65cf"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "debec9b7df5df7d80adc31d572b975bb7f342f875e5b2929a6e902151d3c53cd"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-orchestrate"
  desc "Orchestrate fleets of Claude Code agents across pluggable backends."
  homepage "https://github.com/yasyf/cc-orchestrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-orchestrate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-orchestrate"]
    end
  end

  # No zap stanza required

end
