# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-orchestrate" do
  binary "cc-orchestrate", target: "cco"

  version "0.18.1"

  on_macos do
    on_arm do
      sha256 "d26a8a2b09a1a09e16b9f5958b1d18cd11128a99751b6af278057db6de66bde1"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "716b28c33b226bc745c80050bff9cadd3401b6b52795cf750ba2f0fafa78259b"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "83d4480158da19b249264f03d161bfccb02260010d7d567a91865802495706d8"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cc-orchestrate"
  desc "Orchestrate fleets of Claude Code agents across pluggable backends."
  homepage "https://github.com/yasyf/cc-orchestrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-orchestrate"

  # No zap stanza required
end
