# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-orchestrate" do
  binary "cc-orchestrate", target: "cco"

  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "c4a874e908ced4895fb31abc6bc589523792e2100d8822d3a059bf811577a5fe"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "84c33fac9eaa4aa3c6db2aaf366cce44077cd8784bbd4890305c007ca3d48c63"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "97bb58b034121f5f33ab92afac4501a38961b040bdec584d8b13d6496ac3b595"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0698ad622af773e0cd47740a65a7480388e6a511a3545d9956329a799797ef5f"
      url "https://github.com/yasyf/cc-orchestrate/releases/download/v#{version}/cc-orchestrate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-orchestrate"
  desc "Orchestrate fleets of Claude Code agents across pluggable backends."
  homepage "https://github.com/yasyf/cc-orchestrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-orchestrate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-orchestrate"]
    end
  end

  # No zap stanza required

end
