# Homebrew cask for the cc-pool Notification Center widget (CCPoolStatus.app).
#
# The app is Developer ID signed, notarized, and stapled, so a normal
# quarantined install works. Install with `ccp widget`, or by hand:
#
#   brew install --cask yasyf/tap/cc-pool-status
#
# This file is GENERATED by cc-pool's release.yml (render-formula) and
# pushed here on every tagged release — do not hand-edit; change the
# template at .github/cask/cc-pool-status.rb.tmpl in cc-pool instead.
cask "cc-pool-status" do
  version "0.36.1"
  sha256 "4ddf89504d1f06e6a552d1a340c5f5ca353ce82bf02f65ea2dd04c8b25d8c69a" # app

  url "https://github.com/yasyf/cc-pool/releases/download/v#{version}/cc-pool-status-v#{version}-darwin.zip"
  name "cc-pool Status"
  desc "Notification Center widget showing cc-pool account status"
  homepage "https://github.com/yasyf/cc-pool"

  depends_on macos: :sonoma # parsed with a ">=" comparator: sonoma or newer
  depends_on formula: "cc-pool"

  app "CCPoolStatus.app"

  uninstall quit: "com.yasyf.cc-pool.status"

  zap trash: [
    "~/Library/Containers/com.yasyf.cc-pool.status.widget",
  ]

  caveats <<~EOS
    Launch the app once so macOS discovers the widget:
      open -ga CCPoolStatus
    Then: Notification Center (click the menu-bar clock) → Edit Widgets → "cc-pool".
  EOS
end
