# Homebrew cask for the cc-pool Notification Center widget (CCPoolStatus.app).
#
# The app is Developer ID signed, notarized, and stapled, so a normal
# quarantined install works. Install with `ccp widget`, or by hand:
#
#   brew install --cask yasyf/tap/cc-pool-status
#
# This file is GENERATED by cc-pool's release.yml (render-formula) and
# pushed here on every tagged release — do not hand-edit; change the
# template at .github/cask/cc-pool-status.rb.tmpl in cc-pool instead.
cask "cc-pool-status" do
  version "0.41.0"
  sha256 "8c7bc66939fa1aad04d238f85dfba256dc67eb0a85a626dd033c62921c24f2a8" # app

  url "https://github.com/yasyf/cc-pool/releases/download/v#{version}/cc-pool-status-v#{version}-darwin.zip"
  name "cc-pool Status"
  desc "Notification Center widget showing cc-pool account status"
  homepage "https://github.com/yasyf/cc-pool"

  depends_on macos: :sonoma # parsed with a ">=" comparator: sonoma or newer
  depends_on formula: "cc-pool"

  app "CCPoolStatus.app"

  postflight do
    # An upgrade quits the running app while installing the fresh copy; relaunch
    # it in the background so the widget and the File Provider extension come
    # back without a manual reopen. Best-effort — a headless/no-GUI-session
    # install must not fail the cask over a convenience relaunch.
    system_command "/usr/bin/open", args: ["-g", "#{appdir}/CCPoolStatus.app"], must_succeed: false
  end

  uninstall quit: "com.yasyf.cc-pool.status"

  zap trash: [
    "~/Library/Containers/com.yasyf.cc-pool.status.widget",
    "~/Library/Preferences/com.yasyf.cc-pool.status.plist", # login-item one-shot flag
  ]

  caveats <<~EOS
    Launch the app once so macOS discovers the widget:
      open -ga CCPoolStatus
    Then: Notification Center (click the menu-bar clock) → Edit Widgets → "cc-pool".

    For the File Provider overlay, run the guided setup:
      ccp fp onboard
    Health checks any time: ccp doctor
  EOS
end
