# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-patch" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "300173906ef9053b3c1e5950f6f0a236bf31b6bb135607e8af7f88c329a19de9"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7000407f51f28e8afb3f0a6a9f279afe5b944b24e0f479850eea2bbb72f45241"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a7c5f1e04b834534a9cfa16ab3b95e4eba56aa9378b0855ef10fedb9d54093ea"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c29f2f364c4bb81be8fec04479f480df9e51b7dd7d13fe1e2b3f87224075e743"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-patch"
  desc "Fast mode for Claude Code's delegated agents, re-applied automatically on every update."
  homepage "https://github.com/yasyf/cc-patch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-patch"

  postflight do
    if OS.mac?
      system_command "#{staged_path}/cc-patch", args: ["install-daemons"], must_succeed: false
    end
  end

  # No zap stanza required

end
