# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-patch" do
  version "0.20.2"

  on_macos do
    on_arm do
      sha256 "3be3cf5a7c5ad7821c304ce32ef0295b589287aac7439590c6e20cf74c19a85f"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ecceba1500f6b90e13a741d8f6e74455b52fa738cf0b1aac01b87ba8a1588007"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "cc-patch"
  desc "Fast mode for Claude Code's delegated agents, re-applied automatically on every update."
  homepage "https://github.com/yasyf/cc-patch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-patch"

  postflight do
    if OS.mac?
      # Strip quarantine BEFORE the first exec below, never after: Homebrew marks
      # every cask download com.apple.quarantine, and a quarantined binary's first
      # exec blocks on a syspolicyd assessment that never returns where syspolicyd
      # is wedged — which would hang this postflight, and so `brew install` itself.
      # must_succeed: false because xattr -d exits 1 when the attribute is absent.
      system_command "/usr/bin/xattr",
                     args: ["-d", "com.apple.quarantine", "#{staged_path}/cc-patch"],
                     must_succeed: false
      # Register the launchd agents after install and upgrade so each upgrade
      # re-points them at the new versioned Caskroom binary.
      system_command "#{staged_path}/cc-patch", args: ["install-daemons"], must_succeed: false
    end
  end

  # No zap stanza required
end
