# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-present" do
  version "0.33.0"

  on_macos do
    on_arm do
      sha256 "8fd3558fff85cae1bcfb4b6b40115d6d9197c071b74a991bab94207f81591f89"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a66771493e18cdd90f0dda5812a16d9be4a2463f0660c193d86aaf8950ad1946"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "cc-present"
  desc "Approval boards where every click streams back to the agent."
  homepage "https://github.com/yasyf/cc-present"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-present"

  # No zap stanza required
end
