# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-present" do
  version "0.31.2"

  on_macos do
    on_intel do
      sha256 "eecb668a357fd710a91d45607e5fb3017eea05d7e0180eee0bd1391f76ba2d1b"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff47faa65ad871193d49b45cda316662460a48f6f00265736e0898fccaa92604"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbac6fac6ed4d00e8d8025b50eaf1e03794b1b84a13fec5390b4b4f4963dd8d2"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "334735d9debddfe1e95c54a0ed6d5714a76e0c7f7dcfd8a5c2a0118546047d21"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-present"
  desc "Approval boards where every click streams back to the agent."
  homepage "https://github.com/yasyf/cc-present"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-present"

  # No zap stanza required

end
