# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-patch" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "942f1b147015541d62f92315b604f354c240d1cdae6c2849b0e8830315e5e878"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b32de9ebb090a48386d93e34c5f02a1bcf9fc0d9d0bd90131e9ff5f61976e26a"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "370b8f461f3caed0739dbe9393a874d64cfde967ea67054e5ce94d5d57564397"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "094c18cd20fb9f68a7c0c7a15d604dd9b86293384929f0a15efac07b10b9c39f"
      url "https://github.com/yasyf/cc-patch/releases/download/v#{version}/cc-patch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-patch"
  desc "Fast mode for Claude Code's delegated agents, re-applied automatically on every update."
  homepage "https://github.com/yasyf/cc-patch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-patch"

  postflight do
    if OS.mac?
      system_command "#{staged_path}/cc-patch", args: ["install-daemons"], must_succeed: false
    end
  end

  # No zap stanza required

end
