# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-present" do
  version "0.22.0"

  on_macos do
    on_intel do
      sha256 "b91d2bf4c4015ff0db625be2d9f9420d8f0aa181dce5414a858fb0055a01dcd7"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa79b580ee6c475390621220905d6ecf9a8bb9a56f2c61c259ccf1139e66cbd0"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24b5e995f19865c3601055d5bc8c5a04ecb386dcb4c5f1ad36809efe4ee41ee4"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a07a1931b6a3749aa5b33c1f33b4ade1cd67306fffbebfa26e5388202fb8805a"
      url "https://github.com/yasyf/cc-present/releases/download/v#{version}/cc-present_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-present"
  desc "Approval boards where every click streams back to the agent."
  homepage "https://github.com/yasyf/cc-present"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-present"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-present"]
    end
  end

  # No zap stanza required

end
