# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-review" do
  version "0.30.0"

  on_macos do
    on_intel do
      sha256 "9557ce82dce4535ed82d3c2d811789b1ffcef052f0767576e8fedfc1adeac903"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99bec716164f55f8830faca2ec51cfec839eeac7a12854ab4970238292186e2e"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa2b8d0f938f36d5a5e207f351d8ae5e8939af85113e6d8af0be3b9a2e8b9b6f"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d238ac432fe0ff29393f10a884ea6c1e35c15953481dd3109d3717f9140a3ea"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-review"
  desc "Local code-review daemon + Claude plugin — review what Claude writes in a PR-like web UI and stream feedback back."
  homepage "https://github.com/yasyf/cc-review"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-review"

  # No zap stanza required

end
