# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-review" do
  version "0.36.1"

  on_macos do
    on_arm do
      sha256 "8df1e1b77dbd206b1e1374ec10cd348a1e6e2cff2aace02f913cc8e1e09ebcca"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f31dc4150619a59472b8832e7a8ca5cb637fc8618a78945da4f5fff197d7b5c9"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "cc-review"
  desc "Local code-review daemon + Claude plugin — review what Claude writes in a PR-like web UI and stream feedback back."
  homepage "https://github.com/yasyf/cc-review"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-review"

  # No zap stanza required
end
