# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-remote" do
  version "0.14.4"

  on_macos do
    on_arm do
      sha256 "28721678870df502e2045f1741257fc06f9d0025b0d75057651d39360a7a807e"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d0d11f466b2b712ec2bf482cb32b7f0ed40d4afba324cbfa21e9615452c4402c"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f43c6270ccd3aae4558248d67f7b3a55ef77197fdb9b0b2a5f7aa05b3dff0090"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b809537337da946177b3bba89b7a0455f5aa3b679f54a9b7ff7f1844e9ceda42"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cc-remote"
  desc "Remote agent workspaces, ready with your tools."
  homepage "https://github.com/yasyf/cc-remote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-remote"

  # No zap stanza required
end
