# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-remote" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "7c8a220a93b289ed5f064d3f61ca081b302d1328f741799f0c56267dc0fac00c"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2abe5688a054f97f7c5db69ec0aa2471376f90e8bfcad3e5047c0ea6ef045a95"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a40179205bca78d4fb50fed74774e3f59f73a169f43d3f950f878daecfce6d71"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "49fe71150a3b68ba4e0669b9c8c0d36b2ce31ce6ba74fa3dd4867b8c2736d7f6"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cc-remote"
  desc "Remote agent workspaces, ready with your tools."
  homepage "https://github.com/yasyf/cc-remote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-remote"

  # No zap stanza required
end
