# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-remote" do
  version "0.19.0"

  on_macos do
    on_arm do
      sha256 "80b4124a6ee112633a56605c9cdef3bce1dbacb3b93b55a1e9075796bac2ccf0"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "120583ed8f5108e96af5405b9703109bf4f11595624c57adbaeef82fd39ba0dd"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cc0ea2961afd0b42aa3cd6588a25fa19c8c91b3d72104914a7a451917326f546"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0443f7bca36eed38ec96cd6964927cdee7da1231eb60af119cebed25c064326e"
      url "https://github.com/yasyf/cc-remote/releases/download/v#{version}/cc-remote_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cc-remote"
  desc "Remote agent workspaces, ready with your tools."
  homepage "https://github.com/yasyf/cc-remote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-remote"

  # No zap stanza required
end
