# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-runtime" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "041cece42e34d4c0774f28468a8fa59cc790b081375bcb197e6a4689040795de"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "32b4ef7d23b60583515238418a9d74223a686c20ea2f771d603dbab246716bc6"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0985ccd859684529902e8523f3d14936993b6835a10dfb8ef22fc85d00cd8fe6"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7678204bfac91660e601d11d855754c71388d2d9c8530e25c9cf71c73eccd296"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-runtime"
  desc "Persistent remote delivery for Claude Code questions and notifications."
  homepage "https://github.com/yasyf/cc-runtime"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-runtime"

  # No zap stanza required

end
