# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-runtime" do
  version "0.17.2"

  on_macos do
    on_intel do
      sha256 "36a19ab80dce4a4c9473514e16e20a21d8b7c2eb978b3af2a0ffa8aa74879184"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0a1100876c96219c2a37a6033fdf185720c6fa85b0d6c131d03b0d03e85c6f4"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb83eb4af8539da2e829212c017ef8e7928f961cfd011c725d886067c0f1fafa"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "edd74db93b48ba213213ba7a2f6730b314b445188d39634051879208c8ef8f9b"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-runtime"
  desc "Persistent remote delivery for Claude Code questions and notifications."
  homepage "https://github.com/yasyf/cc-runtime"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-runtime"

  # No zap stanza required

end
