# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-runtime" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "1fb2b1b025cda4d013c7d6ef81747f15d12525cdf036f04d7adb4e0843e58522"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4adfce38b507771588388e541f5c74b5aead89f4e25225e8a3f36a0fc22f7d3c"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ccfc364c61d5d2a7198c7aa4a030a2445720a00cd170239e42be74259fb3fd3f"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aab1f6a37213d899f446847d9340de6b91453a03201b1e7446136b0aeefa61a2"
      url "https://github.com/yasyf/cc-runtime/releases/download/v#{version}/cc-runtime_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-runtime"
  desc "Persistent remote delivery for Claude Code questions and notifications."
  homepage "https://github.com/yasyf/cc-runtime"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-runtime"

  # No zap stanza required

end
