# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-review" do
  version "0.33.3"

  on_macos do
    on_intel do
      sha256 "5f001f4ba160f108e0f201145a112c4c5a648b8cba1ac7906006a7a987506ac9"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7644ced768009f33d17f48d5c75e71dd9b1846f53247b6eb576aa3788251fa2f"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9c257e29094905178922f46d6b091e5eba2efb663782517248baa010dfee922"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f63ce74df5e14e848e4bd624e33f019f52666e807065e1bc62b961beba75b2ca"
      url "https://github.com/yasyf/cc-review/releases/download/v#{version}/cc-review_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-review"
  desc "Local code-review daemon + Claude plugin — review what Claude writes in a PR-like web UI and stream feedback back."
  homepage "https://github.com/yasyf/cc-review"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-review"

  # No zap stanza required

end
