# This file was generated by release-swift.yml. DO NOT EDIT.
cask "cc-sudo" do
  version "0.9.0"
  sha256 "66a6f3e3d6e0c2ed0046a1e5041b6062dfad0c214f6b6edbe36beb6ddbeaaef3"

  url "https://github.com/yasyf/cc-sudo/releases/download/v#{version}/cc-sudo-v#{version}-darwin-universal.zip"
  name "cc-sudo"
  desc "Sudo for Claude, one Touch ID tap per command."
  homepage "https://github.com/yasyf/cc-sudo"

  depends_on macos: ">= :sequoia"

  binary "cc-sudo"

  livecheck do
    skip "Auto-generated on release."
  end
end
