# This file was generated by release-swift.yml. DO NOT EDIT.
cask "cc-sudo" do
  version "0.10.0"
  sha256 "69b70e08b3db20fd90b10d35e335ecb3e088d5df71ee43af844662c63ef42460"

  url "https://github.com/yasyf/cc-sudo/releases/download/v#{version}/cc-sudo-v#{version}-darwin-universal.zip"
  name "cc-sudo"
  desc "Sudo for Claude, one Touch ID tap per command."
  homepage "https://github.com/yasyf/cc-sudo"

  depends_on macos: ">= :sequoia"

  binary "cc-sudo"

  livecheck do
    skip "Auto-generated on release."
  end
end
