# This file was generated by release-swift.yml. DO NOT EDIT.
cask "cc-sudo" do
  version "0.10.2"
  sha256 "84dac6b97e814cd1829f6f26de2a56283b30692d8c71dea47a3f3f4a2a56fbef"

  url "https://github.com/yasyf/cc-sudo/releases/download/v#{version}/cc-sudo-v#{version}-darwin-universal.zip"
  name "cc-sudo"
  desc "Sudo for Claude, one Touch ID tap per command."
  homepage "https://github.com/yasyf/cc-sudo"

  depends_on macos: ">= :sequoia"

  binary "cc-sudo"

  livecheck do
    skip "Auto-generated on release."
  end
end
