# Homebrew cask for the cc-vigil menu-bar app (CCVigil.app).
#
# The app is Developer ID signed, notarized, and stapled, so Gatekeeper
# validates it offline. There is no `service` block: cc-vigil registers
# its per-user LaunchAgent and root LaunchDaemon itself, via SMAppService, during
# the app's first-run setup.
#
#   brew install yasyf/tap/cc-vigil
#
# This file is GENERATED by cc-vigil's release.yml (render-formula) and pushed
# here on every tagged release — do not hand-edit; change the template at
# .github/cask/cc-vigil.rb.tmpl in cc-vigil instead.
cask "cc-vigil" do
  version "0.7.0"
  sha256 "56ed6558cd61e463428b943f2c5db4abd6d45687c40af20b66404df923ba1a86"

  url "https://github.com/yasyf/cc-vigil/releases/download/v#{version}/cc-vigil-v#{version}-darwin.zip"
  name "cc-vigil"
  desc "Keeps your Mac awake while Claude Code agents are working"
  homepage "https://github.com/yasyf/cc-vigil"

  # Apple Silicon only: the bundled cc-transcript parser ships an arm64 slice
  # alone. macOS 15+ matches the app's deployment target (a bare version symbol
  # already means ">=" in Homebrew).
  depends_on arch: :arm64
  depends_on macos: :sequoia

  app "CCVigil.app"

  uninstall quit: "dev.yasyf.cc-vigil"

  zap trash: [
    "~/Library/Application Support/cc-vigil",
  ]

  caveats <<~EOS
    Launch cc-vigil once to run first-run setup — it registers a per-user agent
    and a root helper (approve both under System Settings → General →
    Login Items & Extensions), installs its Claude Code hooks, and puts the
    cc-vigil CLI on your PATH:
      open -a CCVigil

    For a clean removal (services, hooks, CLI symlink), run the in-app uninstall
    from Settings before `brew uninstall --cask cc-vigil`.
  EOS
end
