# This file was generated by GoReleaser. DO NOT EDIT.
cask "cci" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "b983817486c5bbdd9740a8494738db3de6266e019a75fdd6d505ac41c9673e22"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b047485958a1d88fbef00af50d577e8223f14289a48457e7058d56fd2d6275c9"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "258c7c409e42ec83ae88a84f7c32a5ec0a7a5e1c9e70ed46954d73de88f3ebfb"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b279a8941dd7277de1d1f474ee560a799981086c578ce02efb5d3760f001e32a"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cci"
  desc "Local, typed, append-only inbox CLI (cci) and Claude Code plugin for multi-agent drive coordination with bounded reads"
  homepage "https://github.com/yasyf/cc-inbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cci"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cci"]
  end

  # No zap stanza required
end
