# This file was generated by GoReleaser. DO NOT EDIT.
cask "cci" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "41a5f7507237fc2d726c37435665e2ce407010ce1a49b92c9880fa4887f2e992"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1aa81c0dd920562a3cbcd1cecea85b96ac391f44bf406c1502a2614f8320177"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e35b3bcb338750f78c9ea1f311f42c26ade440788719cb8f05414ee0e9da575b"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f9320822d0c027c47f5c994ba6288a671b9594f03b99946aaac13109b9699046"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cci"
  desc "Local, typed, append-only inbox CLI (cci) and Claude Code plugin for multi-agent drive coordination with bounded reads"
  homepage "https://github.com/yasyf/cc-inbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cci"

  # No zap stanza required
end
