# This file was generated by GoReleaser. DO NOT EDIT.
cask "cci" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "07f9bdf2278023c53eae9638a04f5bd0fb681417deb59deca7e99a3fc94ac3f9"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d9ebf3cb241962d77ccf769b422b3688cc83181325121173ec3c902d73df77f7"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3f95f02573cf2962a5bf9cbc728c1423235d5cac67aa0f7bcfddd9b5792ede58"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "88d50241d70f9825625838d407b914b4c1c21548c390945be1d9d9d062257c83"
      url "https://github.com/yasyf/cc-inbox/releases/download/v#{version}/cci_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cci"
  desc "Local, typed, append-only inbox CLI (cci) and Claude Code plugin for multi-agent drive coordination with bounded reads"
  homepage "https://github.com/yasyf/cc-inbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cci"

  # No zap stanza required
end
