# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccx" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7dfae428273b8b5066f8bc0b12673fcad4fb3208664418e672f4dcae3b3af806"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f372d11b25077394f69dbc07c330db5c6e44e01fe3de02946d14c7f718b78239"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb997223eb419b9116be125262a7c992bfb52047e616ffff5843d33108c37e14"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83222568ca0c4761dcc79205e8c4883a29d46e296442cffcc813f903e6f423ff"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccx"
  desc "Compact codebase-context tools for AI agents"
  homepage "https://github.com/yasyf/cc-context"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccx"]
    end
  end

  # No zap stanza required

end
