# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccx" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9cd99d35f1cff2958b29330c463c1fdb5763c601c7efe5d91bed00a44c3098ad"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3347459fb3d43c0f994ebc426e15f8d21b3bfbdff1821a408c817be39709fb96"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f451642948858aa466038de17ba0aa00c0d55f771e4bedb80889cf3cd6716d0"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "558cd94eba330e4bda6a382299666d851404a79dc050680a6405d8605c898721"
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccx"
  desc "Compact codebase-context tools for AI agents"
  homepage "https://github.com/yasyf/cc-context"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccx"]
    end
  end

  # No zap stanza required

end
