# This file was generated by GoReleaser. DO NOT EDIT.
cask "codex-ask" do
  version "1.11.3"

  on_macos do
    on_arm do
      sha256 "ca39ac342db870ab7bc0f6e9a18d780cecb313a8113bd3096e0137efb4368d42"
      url "https://github.com/yasyf/cc-skills/releases/download/v#{version}/codex-ask_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "82ea7ffc77474b6a2e5941251bb223fb5480a8aee2978cd037d9378941bbb00c"
      url "https://github.com/yasyf/cc-skills/releases/download/v#{version}/codex-ask_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "codex-ask"
  desc "The one way the codex plugin runs OpenAI Codex — a pinned, detach-survivable `codex exec` launcher with fan-out mint/collect/await."
  homepage "https://github.com/yasyf/cc-skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codex-ask"

  # No zap stanza required
end
