# This file was generated by GoReleaser. DO NOT EDIT.
cask "codex-ask" do
  version "1.12.0"

  on_macos do
    on_arm do
      sha256 "5a285f4a68f1c3c85a9c48db3a513b90dc352170b3d76742af8abdad278b96ce"
      url "https://github.com/yasyf/cc-skills/releases/download/v#{version}/codex-ask_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "63a78168624ae412e48f9bf7c7fabc84395b7145a8e9f0d826ed75a27fe3f7ea"
      url "https://github.com/yasyf/cc-skills/releases/download/v#{version}/codex-ask_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "codex-ask"
  desc "The one way the codex plugin runs OpenAI Codex — a pinned, detach-survivable `codex exec` launcher with fan-out mint/collect/await."
  homepage "https://github.com/yasyf/cc-skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codex-ask"

  # No zap stanza required
end
