# This file was generated by GoReleaser. DO NOT EDIT.
cask "codex-ask" do
  version "1.13.2"

  on_macos do
    on_arm do
      sha256 "4e16fba44f734ebba0e4cde7587aceba29d36c0a7bd2bccf511ab7fe0b9168bd"
      url "https://github.com/yasyf/cc-skills/releases/download/v#{version}/codex-ask_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f786eabd02f7aa3c1e8318b4497ea40ac40741a16c4d64a4f8c8ae50fe7e931"
      url "https://github.com/yasyf/cc-skills/releases/download/v#{version}/codex-ask_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "codex-ask"
  desc "The one way the codex plugin runs OpenAI Codex — a pinned, detach-survivable `codex exec` launcher with fan-out mint/collect/await."
  homepage "https://github.com/yasyf/cc-skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codex-ask"

  # No zap stanza required
end
