# This file was generated by GoReleaser. DO NOT EDIT.
cask "cookiesync" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "8b686e9decc13f4b640a2e367ae5a7403b5625d679e926623ce9787b4c093dd4"
      url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cd016b0e557e8a831f670ec16271aef0e73d5c3d78353662c0347ddf850a73d"
      url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync_darwin_arm64.tar.gz"
    end
  end

  name "cookiesync"
  desc "Sync your browser cookies across your Macs."
  homepage "https://github.com/yasyf/cookiesync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "cookiesync-keyhelper",
    ]

  binary "cookiesync"

  # No zap stanza required

  caveats <<~EOS
    Wire up the watch daemon and reconcile tick, then track your first browser:

      cookiesync install
  EOS
end
