# Homebrew cask for the cookiesync Secure-Enclave key helper (cookiesync-keyhelper.app).
#
# The .app is Developer ID signed, notarized, and stapled, so a normal quarantined
# install clears Gatekeeper with no xattr/--no-quarantine hook. Install with
# 'cookiesync install', or by hand:
#
#   brew install yasyf/tap/cookiesync-keyhelper
#
# The whole .app must stay intact — the embedded provisioning profile that
# authorizes the Secure Enclave keychain-access-group is bundle-relative — so this
# is an 'app' cask, never a bare 'binary' symlink to the inner executable.
#
# This file is GENERATED by cookiesync's release-pypi.yml publish-cask job and
# pushed here on every tagged release — do not hand-edit; change the template
# in cookiesync's .github/workflows/release-pypi.yml instead.
cask "cookiesync-keyhelper" do
  version "0.1.0"
  sha256 "00a4965772a7e39e410550dbb7d9bfc97ea13cd47630f3ed0c90496e0bf57ec4" # app

  url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync-keyhelper-v#{version}-darwin.zip"
  name "cookiesync key helper"
  desc "Signed Secure-Enclave key helper for cookiesync (Touch ID-gated cookie decryption)"
  homepage "https://github.com/yasyf/cookiesync"

  depends_on macos: :ventura # parsed with a ">=" comparator: ventura or newer

  stage_only true
end
