# Homebrew cask for the cookiesync Secure-Enclave key helper (cookiesync-keyhelper.app).
#
# The .app is Developer ID signed, notarized, and stapled, so a normal quarantined
# install clears Gatekeeper with no xattr/--no-quarantine hook. Install with
# 'cookiesync install', or by hand:
#
#   brew install yasyf/tap/cookiesync-keyhelper
#
# The whole .app must stay intact — the embedded provisioning profile that
# authorizes the Secure Enclave keychain-access-group is bundle-relative, and the
# cookiesync CLI resolves it straight from the Caskroom — so this is a 'stage_only'
# cask, never an 'app' move into /Applications nor a bare 'binary' symlink.
#
# This file is GENERATED by cookiesync's release.yml helper-build job and pushed
# here on every tagged release — do not hand-edit; change the template at
# cookiesync's .github/cask/cookiesync-keyhelper.rb.tmpl instead.
cask "cookiesync-keyhelper" do
  version "0.8.0"
  sha256 "9eba35e041880c7a88b324100d49cf6135b8430919195f200c529cf1484905db" # app

  url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync-keyhelper-v#{version}-darwin.zip"
  name "cookiesync key helper"
  desc "Signed Secure-Enclave key helper for cookiesync (Touch ID-gated cookie decryption)"
  homepage "https://github.com/yasyf/cookiesync"

  depends_on macos: :ventura # parsed with a ">=" comparator: ventura or newer

  stage_only true
end
