# This file was generated by GoReleaser. DO NOT EDIT.
cask "cookiesync" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "65f79a3e5320cc8d8a673becf57cb02f1d7bdfffc7826a593c899ff81b9b3eb4"
      url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f9024c7ca6fa97d9017780cccdb17c167123eeeda042d8adfe593330f865a10"
      url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync_darwin_arm64.tar.gz"
    end
  end

  name "cookiesync"
  desc "Sync your browser cookies across your Macs."
  homepage "https://github.com/yasyf/cookiesync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "cookiesync-keyhelper",
    ]

  binary "cookiesync"

  # No zap stanza required

  caveats <<~EOS
    Wire up the watch daemon and reconcile tick, then track your first browser:

      cookiesync install
  EOS
end
