# This file was generated by GoReleaser. DO NOT EDIT.
cask "cookiesync" do
  version "0.14.1"

  on_macos do
    on_intel do
      sha256 "e54ba9bea363b834a514bfe3e78ab8c6187b3959640fc50a6ea6e05d31d52152"
      url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf7cee2fe727662ce631741603e1d130f1cec299dea5045f5cd0c73f59f2c76c"
      url "https://github.com/yasyf/cookiesync/releases/download/v#{version}/cookiesync_darwin_arm64.tar.gz"
    end
  end

  name "cookiesync"
  desc "Sync your browser cookies across your Macs."
  homepage "https://github.com/yasyf/cookiesync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "cookiesync-keyhelper",
    ]

  binary "cookiesync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/cookiesync"]
    end
    system_command "/bin/launchctl",
                   args:         ["kickstart", "-k", "gui/#{Process.uid}/com.github.yasyf.synckit.helper.cookiesync"],
                   must_succeed: false,
                   print_stderr: false
  end

  # No zap stanza required

  caveats <<~EOS
    Wire up the watch daemon and reconcile tick, then track your first browser:

      cookiesync install
  EOS
end
