# Homebrew cask for the shared fusekit-holder daemon (fusekit-holder.app): one
# Developer ID signed, notarized, stapled holder every fuse-t consumer shares, so they
# all ride one binary identity and one TCC grant.
#
#   brew install --cask yasyf/tap/fusekit-holder
#
# GENERATED by fusekit's release.yml (render-formula) — do not hand-edit; change this
# template at .github/cask/fusekit-holder.rb.tmpl.
cask "fusekit-holder" do
  version "0.36.0"
  sha256 "84dcd0d5e212d27dc539d8787ac119b23c0863a54c4c29d1d08263da1efa9293"

  url "https://github.com/yasyf/fusekit/releases/download/v#{version}/fusekit-holder-v#{version}-darwin.zip"
  name "fusekit-holder"
  desc "Shared fuse-t mount holder for fusekit consumers"
  homepage "https://github.com/yasyf/fusekit"

  depends_on macos: :monterey
  depends_on cask: "macos-fuse-t/homebrew-cask/fuse-t"

  app "fusekit-holder.app"

  postflight do
    # Strip Homebrew's download quarantine so first launch is silent (notarized+stapled).
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/fusekit-holder.app"],
                   must_succeed: false
  end

  uninstall quit: "com.yasyf.fusekit-holder"
end
