# Homebrew cask for the shared fusekit-holder daemon (fusekit-holder.app): one
# Developer ID signed, notarized, stapled holder every fuse-t consumer shares, so they
# all ride one binary identity and one TCC grant.
#
#   brew install --cask yasyf/tap/fusekit-holder
#
# GENERATED by fusekit's release.yml (render-formula) — do not hand-edit; change this
# template at .github/cask/fusekit-holder.rb.tmpl.
cask "fusekit-holder" do
  version "0.29.2"
  sha256 "42bfdc72542955c74b273f3d5d8a2d79b03c393c8fade80bd9d812f3808a1085"

  url "https://github.com/yasyf/fusekit/releases/download/v#{version}/fusekit-holder-v#{version}-darwin.zip"
  name "fusekit-holder"
  desc "Shared fuse-t mount holder for fusekit consumers"
  homepage "https://github.com/yasyf/fusekit"

  depends_on macos: :monterey
  depends_on cask: "macos-fuse-t/homebrew-cask/fuse-t"

  app "fusekit-holder.app"

  uninstall quit: "com.yasyf.fusekit-holder"
end
