# This file was generated by GoReleaser. DO NOT EDIT.
cask "reposync" do
  version "0.27.3"

  on_macos do
    on_intel do
      sha256 "b8994b91048a471c6c4082519b768d58bc16d2d634cdaa5bc6195d6f5f8f55e9"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c0d49c9e19dc0cdad84b3536d19d126a6d387a4f7f2baae752da685cf2988dd"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "43adf0d63575efe215430ad2140f796d71a3ea50a74387b3e7ec074b215801b5"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "70eae001143859e84cbe801fae7a74336915334c1ca9ed341237ddda8f974408"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_linux_arm64.tar.gz"
    end
  end

  name "reposync"
  desc "Keep git repos in sync across your remote hosts."
  homepage "https://github.com/yasyf/reposync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jj",
    ]

  binary "reposync"

  # No zap stanza required

end
