# This file was generated by GoReleaser. DO NOT EDIT.
cask "reposync" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "93365516974592d8c2e0472c7c8953da435f100e7b1730fdd31b3e2883bba279"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a6eaba01bed7463e1db04298fcb529e0954767cab30c304d52007e74aeed6b9"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b670ac06f27fdbc813cc2871a495ae96328f94826875918a23a9c59e39fa5b4"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d18e1906289be8ca78ecdbb9784c5f4d2d18392e4e732f7522d1a365eaf68f8b"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_linux_arm64.tar.gz"
    end
  end

  name "reposync"
  desc "Keep git repos in sync across your remote hosts."
  homepage "https://github.com/yasyf/reposync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "watchman",
    ]

  binary "reposync"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reposync"]
    end
  end

  # No zap stanza required

end
