# This file was generated by GoReleaser. DO NOT EDIT.
cask "reposync" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "1236bcab7e6d4635b805a3a7180a48f44c50cd3af0317d9d6b0818ce0c42560c"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bb47bf066ecf9f2c016f6c1fd7456c8f513ee294b58cb1aa67e53b5a8e1c0d2"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82138e0883bbd2f832e286572af841b473dc940bf74e6da55a2f1ef48ed4423e"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b47b88d1235743bc3fca216d55194cf006deef139dee03ad4e3916b2af44c2f"
      url "https://github.com/yasyf/reposync/releases/download/v#{version}/reposync_linux_arm64.tar.gz"
    end
  end

  name "reposync"
  desc "Keep git repos in sync across your remote hosts."
  homepage "https://github.com/yasyf/reposync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jj",
      "watchman",
    ]

  binary "reposync"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reposync"]
    end
  end

  # No zap stanza required

end
