# This file was generated by GoReleaser. DO NOT EDIT.
cask "slop-cop" do
  version "0.1.37"

  on_macos do
    on_intel do
      sha256 "02af3fef24b4455828d8f018a9773164702041a68a602eabf26b9027154b094a"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0cf82ea7dd71e68a103158880a0f5d34bd069ad654d1de4bfc04da3d35e5823e"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2063b3e6ab2453d988138f8d21fd9da555e6b948d06f853550f1d139c618c1b3"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2b4547543c9bae078909fa484474b21c3b1d78b46bc04f92149ecc9963eda8e"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_linux_arm64.tar.gz"
    end
  end

  name "slop-cop"
  desc "Detect the rhetorical and structural tells of LLM-generated prose and emit a structured JSON report."
  homepage "https://github.com/yasyf/slop-cop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slop-cop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/slop-cop"]
    end
  end

  # No zap stanza required

end
