# This file was generated by GoReleaser. DO NOT EDIT.
cask "slop-cop" do
  version "0.1.18"

  on_macos do
    on_intel do
      sha256 "e8719166deb8fa865342443d58fc7320488966e9f76ee8030dae25db0f7eecb6"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4109b83059992604e54685cecb2a7f66de43db4e772f0c5397fb2ebbae597250"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f480ba8a1bd879ae44f6bf9d11a151a1a2843724588712317faad7c57a3d62d"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "123578ecfff0883c6e681bc7d7316c4141a072ba4badb4852dd9756f34202c85"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_linux_arm64.tar.gz"
    end
  end

  name "slop-cop"
  desc "Detect the rhetorical and structural tells of LLM-generated prose and emit a structured JSON report."
  homepage "https://github.com/yasyf/slop-cop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slop-cop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/slop-cop"]
    end
  end

  # No zap stanza required

end
