# This file was generated by GoReleaser. DO NOT EDIT.
cask "slop-cop" do
  version "0.1.25"

  on_macos do
    on_intel do
      sha256 "52bedf00c743a84ec53d9686e9db6f56857da08ff4eaf682a7ff51148d76af8a"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4e17091a0f080071ca9e7ddfd3498ec5ae93479b54d004de1731133c57150d6"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "982ac48606e4b6f1aae99abcefa37d759764257817771baab60a3b329e4eac7c"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ca4d5a04189fa41ad0e033945ba876ef013cc1f07e6a3914e890257d83c0325"
      url "https://github.com/yasyf/slop-cop/releases/download/v#{version}/slop-cop_linux_arm64.tar.gz"
    end
  end

  name "slop-cop"
  desc "Detect the rhetorical and structural tells of LLM-generated prose and emit a structured JSON report."
  homepage "https://github.com/yasyf/slop-cop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slop-cop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/slop-cop"]
    end
  end

  # No zap stanza required

end
