# This file was generated by release-swift.yml. DO NOT EDIT.
cask "swift-hello" do
  version "0.1.1"
  sha256 "791ae950874e30fbfc743ae88e909d857748eeaebbb804cede5aadb98011ba6d"

  url "https://github.com/yasyf/swift-hello/releases/download/v#{version}/swift-hello-v#{version}-darwin-universal.zip"
  name "swift-hello"
  desc "Scratch canary: sign & notarize & cask via release-swift.yml"
  homepage "https://github.com/yasyf/swift-hello"

  depends_on macos: ">= :sequoia"

  binary "swift-hello"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swift-hello"]
    end
  end

  livecheck do
    skip "Auto-generated on release."
  end
end
