# This file was generated by release-swift.yml. DO NOT EDIT.
cask "swift-hello" do
  version "0.1.0"
  sha256 "a127227c77150d5a2888f7292b0133a967f79d288769055e4254cfc6da0bca2b"

  url "https://github.com/yasyf/swift-hello/releases/download/v#{version}/swift-hello-v#{version}-darwin-universal.zip"
  name "swift-hello"
  desc "Scratch canary for the shared Swift release pipeline (repo-bootstrap swift layer)"
  homepage "https://github.com/yasyf/swift-hello"

  depends_on macos: ">= :sequoia"

  binary "swift-hello"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swift-hello"]
    end
  end

  livecheck do
    skip "Auto-generated on release."
  end
end
