# Homebrew formula for the fixed signed Captain Hook deployment.
#
# GENERATED by release-pypi.yml from a verified signed, notarized, and stapled
# GitHub release asset. Edit this template, not the tap copy.
class CaptainHook < Formula
  desc "Fast, configurable hooks for agent coding tools"
  homepage "https://github.com/yasyf/captain-hook"
  version "12.34.0"
  license "PolyForm-Noncommercial-1.0.0"
  url "https://github.com/yasyf/captain-hook/releases/download/v12.34.0/captain-hook-v12.34.0-darwin.zip", using: :nounzip
  sha256 "e7d0d3c7d6319d2758ed469da29c2c73311782c608fa6bc0dc86b1d8e8cbf18a"

  depends_on macos: :sequoia

  preserve_rpath

  def install
    system "/usr/bin/ditto", "-x", "-k", cached_download, "."
    system "/usr/bin/codesign", "--verify", "--deep", "--strict", "--verbose=2", "Captain Hook.app"
    libexec.install "Captain Hook.app"
    # bash, not sh: binrun runs this wrapper as the descriptor's version command on
    # every resolve, and an endpoint-security agent that deep-inspects /bin/sh can
    # put seconds on each exec, enough to blow daemonkit's 10 s version timeout.
    (bin/"capt-hook-host").write <<~SH
      #!/bin/bash
      exec "$HOME/Applications/Captain Hook.app/Contents/Helpers/capt-hookd" "$@"
    SH
  end

  def caveats
    <<~EOS
      Captain Hook's signed helper is deployment-owned at:
        ~/Applications/Captain Hook.app

      Repair or reconverge it with:
        capt-hook helper install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/capt-hook-host version")
    system "/usr/bin/codesign", "--verify", "--deep", "--strict", "--verbose=2", libexec/"Captain Hook.app"
  end
end
