# Homebrew formula for cc-notes. Installs the prebuilt binary for the current
# platform from cc-notes' GitHub Releases — no Go toolchain needed.
#
#   brew install yasyf/tap/cc-notes
#
# Asset names, scripts/install.sh, and the render-formula substitutions in
# .github/workflows/release.yml must change in lockstep.
#
# GENERATED by cc-notes' release.yml (render-formula) from this template — edit the
# template at .github/formula/cc-notes.rb.tmpl, not the tap copy.
class CcNotes < Formula
  desc "Git-native notes and tasks layer for agents"
  homepage "https://github.com/yasyf/cc-notes"
  version "0.46.2"
  license "PolyForm-Noncommercial-1.0.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    resource "helper" do
      url "https://github.com/yasyf/cc-notes/releases/download/v0.46.2/cc-notes-helper-v0.46.2-darwin.zip", using: :nounzip
      sha256 "c34a1f810c29b3f1738bccf1b9a97c394555d3ad0ce7cd38406aa356ddf209b7"
    end

    on_arm do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_darwin_arm64"
      sha256 "0c75aa0ce97c368bd10e2e152fd33e3f02b6d8942d2799a0fb1d398dc0889449"
    end
    on_intel do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_darwin_amd64"
      sha256 "58dd9637f28c66af4e9c82712a55730ad44f4fdf78246f60ede2d2ac0e19e043"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_linux_amd64"
      sha256 "7d1144b04b521dd572a8f77bbaf8980ce968c99de14fbd9e9d9b35a8686cf44e"
    end
    on_arm do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_linux_arm64"
      sha256 "ddc05d6b94f79dfd2af45f53c1109b6797df4afcf10e3fa0d271634e1cf796cf"
    end
  end

  def install
    # The release asset is a bare binary staged under its asset name.
    bin.install Dir["cc-notes_*"].first => "cc-notes"
    if OS.mac?
      resource("helper").stage do
        system "/usr/bin/ditto", "-x", "-k", resource("helper").cached_download, "."
        system "/usr/bin/codesign", "--verify", "--strict", "--verbose=2", "CCNotesHelper.app"
        libexec.install "CCNotesHelper.app"
      end
    end
    bin.install_symlink "cc-notes" => "ccn"
  end

  def caveats
    return if OS.linux?

    <<~EOS
      Install and activate the fixed signed helper explicitly:
        cc-notes package install
    EOS
  end

  test do
    # Release binaries print "<tag> (<commit>)", e.g. "v0.2.0 (ab12cd3)".
    assert_match version.to_s, shell_output("#{bin}/cc-notes version")
  end
end
