# Homebrew formula for cc-notes. Installs the prebuilt binary for the current
# platform from cc-notes' GitHub Releases — no Go toolchain needed.
#
#   brew install yasyf/tap/cc-notes
#
# Asset names, scripts/install.sh, and the render-formula substitutions in
# .github/workflows/release.yml must change in lockstep.
#
# GENERATED by cc-notes' release.yml (render-formula) from this template — edit the
# template at .github/formula/cc-notes.rb.tmpl, not the tap copy.
class CcNotes < Formula
  desc "Git-native notes and tasks layer for agents"
  homepage "https://github.com/yasyf/cc-notes"
  version "0.63.8"
  license "PolyForm-Noncommercial-1.0.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    resource "helper" do
      url "https://github.com/yasyf/cc-notes/releases/download/v0.63.8/cc-notes-helper-v0.63.8-darwin.zip", using: :nounzip
      sha256 "97133d4743d33f51e83f9108f0413ec0526c850edf7c1b29982f04994a21a1f8"
    end

    on_arm do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_darwin_arm64"
      sha256 "0d063d58b88191db24c0ddee1be8bba6578e243b37de69cc38c21dbaf19d9e6b"
    end
    on_intel do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_darwin_amd64"
      sha256 "afaef90bc7c6e41d530c33a1ee065caaae4d4061ab03780f4d11f80d3adf0fef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_linux_amd64"
      sha256 "8e5ad4d75da61c4c1857353ae1a6bedd53abac74bee060e7a5c8600b1d993659"
    end
    on_arm do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_linux_arm64"
      sha256 "268779f82272cb9514e7c529a356c2360a9af4853f95589e997a31b470be1a54"
    end
  end

  preserve_rpath

  def install
    # The release asset is a bare binary staged under its asset name.
    bin.install Dir["cc-notes_*"].first => "cc-notes"
    if OS.mac?
      resource("helper").stage do
        system "/usr/bin/ditto", "-x", "-k", resource("helper").cached_download, "."
        system "/usr/bin/codesign", "--verify", "--strict", "--verbose=2", "CCNotesHelper.app"
        libexec.install "CCNotesHelper.app"
      end
      # opt_libexec, not libexec: Homebrew unlinks the active keg mid-upgrade,
      # and the packaged copy is the one that lands the deployment.
      (bin/"cc-notes-host").write <<~SH
        #!/bin/bash
        exec "#{opt_libexec}/CCNotesHelper.app/Contents/MacOS/CCNotesHelper" "$@"
      SH
    end
    bin.install_symlink "cc-notes" => "ccn"
  end

  def caveats
    return if OS.linux?

    <<~EOS
      Install and activate the fixed signed helper explicitly:
        cc-notes package install
    EOS
  end

  test do
    # Release binaries print "<tag> (<commit>)", e.g. "v0.2.0 (ab12cd3)".
    assert_match version.to_s, shell_output("#{bin}/cc-notes version")
    if OS.mac?
      system "/usr/bin/codesign", "--verify", "--deep", "--strict", "--verbose=2", libexec/"CCNotesHelper.app"
      assert_match version.to_s, shell_output("#{bin}/cc-notes-host version")
    end
  end
end
