# Homebrew formula for cc-notes. Installs the prebuilt binary for the current
# platform from cc-notes' GitHub Releases — no Go toolchain needed.
#
#   brew install yasyf/tap/cc-notes
#
# Asset names, scripts/install.sh, and the render-formula substitutions in
# .github/workflows/release.yml must change in lockstep.
#
# GENERATED by cc-notes' release.yml (render-formula) from this template — edit the
# template at .github/formula/cc-notes.rb.tmpl, not the tap copy.
class CcNotes < Formula
  desc "Git-native notes and tasks layer for agents"
  homepage "https://github.com/yasyf/cc-notes"
  version "0.57.0"
  license "PolyForm-Noncommercial-1.0.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    resource "helper" do
      url "https://github.com/yasyf/cc-notes/releases/download/v0.57.0/cc-notes-helper-v0.57.0-darwin.zip", using: :nounzip
      sha256 "2559730b67ccc99ea538ef244ce7128b44ea336a0f56f1cbebb8903640e46feb"
    end

    on_arm do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_darwin_arm64"
      sha256 "431cdc1f594c474d27687dba4ba3e59832e4339e7c05cd4bc4a1bc93350f272b"
    end
    on_intel do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_darwin_amd64"
      sha256 "60c3b541a5101ff4971a3068c59800d7cd51b19dd21a3bddf8c0897406590203"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_linux_amd64"
      sha256 "76b167a142379f3430c77d4a5d9754f373327c28608769fab854ae96614eb4b2"
    end
    on_arm do
      url "https://github.com/yasyf/cc-notes/releases/download/v#{version}/cc-notes_linux_arm64"
      sha256 "5ceb2ef3e5d60044769acdca56f05cda9f05c2b5b70a2884d0abcc5812e70ac3"
    end
  end

  preserve_rpath

  def install
    # The release asset is a bare binary staged under its asset name.
    bin.install Dir["cc-notes_*"].first => "cc-notes"
    if OS.mac?
      resource("helper").stage do
        system "/usr/bin/ditto", "-x", "-k", resource("helper").cached_download, "."
        system "/usr/bin/codesign", "--verify", "--strict", "--verbose=2", "CCNotesHelper.app"
        libexec.install "CCNotesHelper.app"
      end
      # opt_libexec, not libexec: Homebrew unlinks the active keg mid-upgrade,
      # and the packaged copy is the one that lands the deployment.
      (bin/"cc-notes-host").write <<~SH
        #!/bin/bash
        exec "#{opt_libexec}/CCNotesHelper.app/Contents/MacOS/CCNotesHelper" "$@"
      SH
    end
    bin.install_symlink "cc-notes" => "ccn"
  end

  def caveats
    return if OS.linux?

    <<~EOS
      Install and activate the fixed signed helper explicitly:
        cc-notes package install
    EOS
  end

  test do
    # Release binaries print "<tag> (<commit>)", e.g. "v0.2.0 (ab12cd3)".
    assert_match version.to_s, shell_output("#{bin}/cc-notes version")
    if OS.mac?
      system "/usr/bin/codesign", "--verify", "--deep", "--strict", "--verbose=2", libexec/"CCNotesHelper.app"
      assert_match version.to_s, shell_output("#{bin}/cc-notes-host version")
    end
  end
end
