# Homebrew formula for cc-pool. Installs the prebuilt universal binary from
# GitHub Releases — no Go toolchain needed.
#
#   brew install yasyf/tap/cc-pool
#
# One prebuilt pure-Go universal binary (arm64 + amd64) ships per release.
#
# This file is GENERATED by cc-pool's release.yml (render-formula) and
# pushed here on every tagged release — do not hand-edit; change the
# template at .github/formula/cc-pool.rb.tmpl in cc-pool instead.
class CcPool < Formula
  desc "Predictive multi-account load-balancing for Claude Code"
  homepage "https://github.com/yasyf/cc-pool"
  url "https://github.com/yasyf/cc-pool/releases/download/v0.67.0/cc-pool-v0.67.0-darwin-universal.tar.gz"
  sha256 "65f9939d5592cdcb425b1dd5160084ce50a3b41113c2f3713247b35bbc285e92" # pure
  license "PolyForm-Noncommercial-1.0.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on :macos
  preserve_rpath

  resource "status_app" do
    url "https://github.com/yasyf/cc-pool/releases/download/v0.67.0/cc-pool-status-v0.67.0-darwin.zip", using: :nounzip
    sha256 "05456780cdae869073763df97f8a4ac05cf357ba2119232185d13fb935e48f24"
  end

  def install
    bin.install "cc-pool"
    resource("status_app").stage do
      system "/usr/bin/ditto", "-x", "-k", resource("status_app").cached_download, "."
      staged_app = Pathname("CCPoolStatus.app")
      odie "staged status app is missing" unless staged_app.directory?
      odie "staged status app has no Contents" unless (staged_app/"Contents").directory?
      system "/usr/bin/codesign", "--verify", "--deep", "--strict", "--verbose=2", staged_app
      system "/usr/bin/xcrun", "stapler", "validate", staged_app
      system "/usr/sbin/spctl", "--assess", "--type", "execute", "--verbose=4", staged_app
      app_version = Utils.safe_popen_read(
        "/usr/libexec/PlistBuddy", "-c", "Print :CFBundleShortVersionString",
        staged_app/"Contents/Info.plist"
      ).strip
      odie "CCPoolStatus.app version #{app_version} does not match #{version}" if app_version != version.to_s
      libexec.install staged_app
    end
    bin.install_symlink "cc-pool" => "ccp"
  end

  def caveats
    <<~EOS
      Get started:
        ccp package install # install and activate this release's signed application
        ccp service install # install and start the account daemon
        ccp             # walks you through pooling your subscriptions
        ccp run         # launch claude on the emptiest account

      `ccp package install` verifies the formula's exact signed application,
      installs it outside Homebrew's sandbox into:
        ~/Applications/CCPoolStatus.app

      daemonkit owns the user LaunchAgent. Homebrew does not install or control
      a second daemon service.

      Plain `claude` on ~/.claude keeps working untouched.

      Before `brew uninstall`, run `ccp service uninstall` and then
      `ccp package uninstall`.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cc-pool --version")
    assert_match "emptiest account", shell_output("#{bin}/ccp --help")
  end
end
