# Homebrew formula for cc-squash. Installs the prebuilt universal binaries
# (ccs control plane + ccs-proxy data plane) from GitHub Releases — no Go
# or Rust toolchain needed.
#
#   brew install yasyf/tap/cc-squash
#
# This file is GENERATED by cc-squash's release.yml from
# .github/formula/cc-squash.rb.tmpl and pushed here on every tagged release —
# do not hand-edit; change the template in cc-squash instead.
class CcSquash < Formula
  desc "Augmented auto-compaction for long-running Claude Code sessions"
  homepage "https://github.com/yasyf/cc-squash"
  url "https://github.com/yasyf/cc-squash/releases/download/v0.3.1/cc-squash-v0.3.1-darwin-universal.tar.gz"
  sha256 "4467be5001a8ed71b8cae986cd4a6f31e4559e68c941c55912b6636458c17639"
  license "PolyForm-Noncommercial-1.0.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on :macos

  def install
    bin.install "ccs", "ccs-proxy"
  end

  # Run the daemon as a USER LaunchAgent (no sudo): it supervises the
  # ccs-proxy data plane on a per-user localhost socket. `brew services
  # start cc-squash` installs ~/Library/LaunchAgents/homebrew.mxcl.cc-squash.plist.
  service do
    run [opt_bin/"ccs", "daemon"]
    keep_alive true
    run_at_load true
    environment_variables PATH: std_service_path_env
    log_path "#{Dir.home}/.cc-squash/daemon.log"
    error_log_path "#{Dir.home}/.cc-squash/daemon.log"
  end

  def caveats
    <<~EOS
      Start the background daemon:
        brew services start cc-squash

      Then point Claude Code at the proxy for continuous compaction:
        ANTHROPIC_BASE_URL=$(ccs url) ENABLE_TOOL_SEARCH=true claude

      Bare `claude` keeps working untouched.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccs --version")
  end
end
