# Homebrew formula for ccx (cc-context). Installs the prebuilt binary for the
# current platform from cc-context's GitHub Releases — no toolchain needed.
# `brew install --HEAD` builds from source instead: the format engine is a WASM
# blob built from Rust (the repo's `task wasm`), so the head block adds `rustup`
# and `go-task` as build-only deps and runs the WASM build before the Go compile.
#
#   brew install yasyf/tap/ccx
#
# This file is generated by cc-context's release.yml from .github/formula/ccx.rb.tmpl
# on every stable tag — edit the template there, not the tap copy. The release job
# fills the version placeholder with the v-stripped release version and the four
# per-platform sha256 placeholders with the archive checksums from dist/checksums.txt.
class Ccx < Formula
  desc "Compact codebase-context tools for AI agents"
  homepage "https://github.com/yasyf/cc-context"
  version "0.65.51"
  license "PolyForm-Noncommercial-1.0.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # HEAD builds the format-core WASM engine from source (task wasm -> cargo -> a
  # wasm32-unknown-unknown blob) and then the Go binary that go:embed's it.
  # Homebrew's `rust` ships no wasm32 std, so HEAD depends on `rustup` and
  # provisions the toolchain + target into the build sandbox, mirroring
  # release.yml's pre-build.
  head do
    url "https://github.com/yasyf/cc-context.git", branch: "main"
    depends_on "go" => :build
    depends_on "go-task" => :build
    depends_on "rustup" => :build
  end

  # ast-grep powers the structural search/replace engine; uv runs semble (via uvx)
  # for the semantic search/related ops and the pydantic-monty driver for the
  # ccx exec sandbox. Both are required at runtime.
  depends_on "ast-grep"
  depends_on "uv"

  on_macos do
    on_arm do
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_darwin_arm64.tar.gz"
      sha256 "c2fb2b80416a916ae610509cf16dc1382862298beb6c98a1bddedd22db59d471"
    end
    on_intel do
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_darwin_amd64.tar.gz"
      sha256 "618b9ea2afc34396ba2a1020b666dc9b2809c9763e0408ea0139c44413c7efad"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_linux_arm64.tar.gz"
      sha256 "ca55c44ff6dacc1660427c7972a976837eece20ee9e089f7e594d5f959496486"
    end
    on_intel do
      url "https://github.com/yasyf/cc-context/releases/download/v#{version}/ccx_#{version}_linux_amd64.tar.gz"
      sha256 "8087bb41b8666e490b3765dcb54f6fad1fcdf559cced82fa7bb18814040165cd"
    end
  end

  def install
    if build.head?
      ENV["RUSTUP_HOME"] = "#{buildpath}/.rustup"
      ENV["CARGO_HOME"] = "#{buildpath}/.cargo"
      system "rustup", "toolchain", "install", "stable", "--profile", "minimal",
             "--target", "wasm32-unknown-unknown"
      system "rustup", "default", "stable"
      # Build the go:embed'd format-core WASM engine (task wasm -> scripts/build-wasm.sh)
      # before the Go compile that embeds it.
      system "task", "wasm"
      ENV["CGO_ENABLED"] = "0"
      ldflags = "-s -w -X github.com/yasyf/cc-context/internal/version.Version=#{version}"
      system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"ccx"), "./cmd/ccx"
    else
      # brew auto-extracts the release tarball; install the bare binary.
      bin.install "ccx"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccx --version")
  end
end
