# Homebrew formula for synckitd. Installs the prebuilt binary for the current
# platform from synckit's GitHub Releases — no Go toolchain needed.
# `brew install --HEAD` builds (pure Go) from source instead.
#
#   brew install yasyf/tap/synckitd
#
# This file is generated by synckit's release.yml from
# .github/formula/synckitd.rb.tmpl on every stable tag — edit the template here,
# not the tap copy. The release job fills 0.14.0 with the v-stripped release
# version and the four __SHA_*__ tokens with the archive checksums from
# dist/checksums.txt.
class Synckitd < Formula
  desc "Generic per-machine sync daemon that drives synckit consumers (cookiesync, reposync)"
  homepage "https://github.com/yasyf/synckit"
  version "0.14.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  head do
    url "https://github.com/yasyf/synckit.git", branch: "main"
    depends_on "go" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_darwin_arm64.tar.gz"
      sha256 "664c146f8de14941f24f0094147bc429f778c723cb394f60e83b971f22fe8a72"
    end
    on_intel do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_darwin_amd64.tar.gz"
      sha256 "8cde40b81a7eaab436df2611925c1c4b7d8cc8b3917d9fe2c82322073cf4ef0c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_linux_arm64.tar.gz"
      sha256 "2988fe4f8aedb40ae04da14487209a06b3cf7ec7ca738dbc3544e00c48545b9f"
    end
    on_intel do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_linux_amd64.tar.gz"
      sha256 "663e075d047358c684345b7cb240a57bf6a1191699e005a8b9a0ed40af1ec006"
    end
  end

  def install
    if build.head?
      ENV["CGO_ENABLED"] = "0"
      ldflags = "-s -w -X main.version=#{version}"
      system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"synckitd"), "./cmd/synckitd"
    else
      # brew auto-extracts the release tarball; install the bare binary.
      bin.install "synckitd"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/synckitd --version")
  end
end
