# Homebrew formula for synckitd. Installs the prebuilt binary for the current
# platform from synckit's GitHub Releases — no Go toolchain needed.
# `brew install --HEAD` builds (pure Go) from source instead.
#
#   brew install yasyf/tap/synckitd
#
# This file is generated by synckit's release.yml from
# .github/formula/synckitd.rb.tmpl on every stable tag — edit the template here,
# not the tap copy. The release job fills 0.11.0 with the v-stripped release
# version and the four __SHA_*__ tokens with the archive checksums from
# dist/checksums.txt.
class Synckitd < Formula
  desc "Generic per-machine sync daemon that drives synckit consumers (cookiesync, reposync)"
  homepage "https://github.com/yasyf/synckit"
  version "0.11.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  head do
    url "https://github.com/yasyf/synckit.git", branch: "main"
    depends_on "go" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_darwin_arm64.tar.gz"
      sha256 "a99f0494a9a374417cff1cf3453bcd46a9a93ad7c5422277d736c38f5225d9fe"
    end
    on_intel do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_darwin_amd64.tar.gz"
      sha256 "0d2897594d3e3b635f0b7b54983d3e7e18f340b192aad0dcc2887a63b893a1fa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_linux_arm64.tar.gz"
      sha256 "8e39d26b53dd3655a5f31ae05025181425ac8209ca3dc83c9be190ab1ebd1646"
    end
    on_intel do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_linux_amd64.tar.gz"
      sha256 "05d22aa5b0887eec4b0a70bb8a1737436db7f93e891a1cccb3438b6d966aab8b"
    end
  end

  def install
    if build.head?
      ENV["CGO_ENABLED"] = "0"
      ldflags = "-s -w -X main.version=#{version}"
      system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"synckitd"), "./cmd/synckitd"
    else
      # brew auto-extracts the release tarball; install the bare binary.
      bin.install "synckitd"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/synckitd --version")
  end
end
