# Homebrew formula for synckitd. Installs the prebuilt binary for the current
# platform from synckit's GitHub Releases — no Go toolchain needed.
# `brew install --HEAD` builds (pure Go) from source instead.
#
#   brew install yasyf/tap/synckitd
#
# This file is generated by synckit's release.yml from
# .github/formula/synckitd.rb.tmpl on every stable tag — edit the template here,
# not the tap copy. The release job fills 0.27.0 with the v-stripped release
# version and the four __SHA_*__ tokens with the archive checksums from
# dist/checksums.txt.
class Synckitd < Formula
  desc "Generic per-machine sync daemon that drives synckit consumers (cookiesync, reposync)"
  homepage "https://github.com/yasyf/synckit"
  version "0.27.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  head do
    url "https://github.com/yasyf/synckit.git", branch: "main"
    depends_on "go" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_darwin_arm64.tar.gz"
      sha256 "bea6abea668fd8e12648967e09661295e4cc728b6de2dff248e95be3011d398f"
    end
    on_intel do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_darwin_amd64.tar.gz"
      sha256 "092e4fd633b43c1295f9979a2011abfef036472a01d4664c715e60cb70a3d744"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_linux_arm64.tar.gz"
      sha256 "b000cd2405b7dd69d74bea5b565c4ef1333a61d6858fb37358de1d57f42c0f59"
    end
    on_intel do
      url "https://github.com/yasyf/synckit/releases/download/v#{version}/synckitd_#{version}_linux_amd64.tar.gz"
      sha256 "891bb243c99b53d2f10df8e2cf3bf80ab98bb8669018d7b8d9a6b0448a7b66d8"
    end
  end

  def install
    if build.head?
      ENV["CGO_ENABLED"] = "0"
      ldflags = "-s -w -X main.version=#{version}"
      system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"synckitd"), "./cmd/synckitd"
    else
      # brew auto-extracts the release tarball; install the bare binary.
      bin.install "synckitd"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/synckitd --version")
  end
end
